guardian/content-authorisation-proxy

- .prout.json
- build.sbt
- project/plugins.sbt
- src/main/scala/com/gu/subscriptions/cas/directives/HealthCheckDirective.scala
http://www.theguardian.com/info/developer-blog/2015/feb/03/prout-is-your-pull-request-out
https://github.com/guardian/prout
cc @tudorraul
> Add Prout, so we can see when our pull requests go out

- .prout.json
...now that we've gone live on handling traffic.
cc @jennysivapalan
> Point Prout to the production url

- build.sbt
- src/main/scala/com/gu/subscriptions/cas/bootstrap/CASService.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ErrorRoute.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ZuoraDirective.scala
- src/main/scala/com/gu/subscriptions/cas/model/SubscriptionRequest.scala
- src/main/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocol.scala
- src/main/scala/com/gu/subscriptions/cas/service/ZuoraSubscriptionService.scala
- src/main/scala/com/gu/subscriptions/cas/service/package.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
- src/test/scala/com/gu/subscriptions/cas/service/ZuoraSubscriptionServiceTest.scala
Also:
- Add some tests around routing
- Uniformly respond with JSON even for errors
> Fail with 400 when a subs request is malformed

- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
Reverts guardian/content-authorisation-proxy#22
> Revert "Test request and response transformation during proxying"

- build.sbt
- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/service/ZuoraSubscriptionService.scala
- src/main/scala/com/gu/subscriptions/cas/service/package.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
Returns a 400 instead of a 500 if Zuora subscription expiration is not found.
> Zuora error handling

- build.sbt
- src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
- src/main/scala/com/gu/subscriptions/cas/bootstrap/CASService.scala
- src/main/scala/com/gu/subscriptions/cas/bootstrap/ServiceInitialiser.scala
- src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/service/package.scala
- src/main/scala/com/gu/subscriptions/cas/service/zuora/ZuoraSubscriptionService.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ZuoraDirectiveTest.scala
- src/test/scala/com/gu/subscriptions/cas/service/ZuoraSubscriptionServiceTest.scala
Added Tests and Refactored code
https://trello.com/c/iguT1oES/141-additional-custom-data-fields-activation-date
Refactored code to return the Future based on the Subscription Name
Added New Tests for ZuoraDirective
> Activation date

- build.sbt
- src/main/scala/com/gu/subscriptions/cas/config/Zuora.scala
- src/main/scala/com/gu/subscriptions/cas/model/Implicits.scala
- src/main/scala/com/gu/subscriptions/cas/service/package.scala
- src/main/scala/com/gu/subscriptions/cas/service/zuora/ZuoraSubscriptionService.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
- src/test/scala/com/gu/subscriptions/cas/model/ImplicitsSpec.scala
Ensured all references from membership common work are now correct in content-auth-proxy.
> Membership common consolidation

- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
Updating timeout for CAS proxy connecting to CAS as the timeout was a little aggresive.
> Updated the timeout from 2 to 3 seconds

- cloudformation/content-authorisation-proxy.cf.json
It looks like this is missing the call to `apt-get upgrade`.
> Add call to `apt-get upgrade`

- cloudformation/content-authorisation-proxy.cf.json
- src/main/scala/com/gu/subscriptions/cas/bootstrap/CASService.scala
Adding extra info to the Generic error log, as it's not printing details from the Cause/Throwable.
cc @rtyley
> Adding extra info to the Generic error log line

- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/monitoring/Histogram.scala
Also a performance (memory) tweak on .toSeq to .toStream.
cc @tomverran
> Adding counts to report plus a few more situations being charted.

- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ZuoraDirective.scala
- src/main/scala/com/gu/subscriptions/cas/model/AuthorisationRequest.scala
- src/main/scala/com/gu/subscriptions/cas/model/SubscriptionRequest.scala
- src/main/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocol.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ZuoraDirectiveTest.scala
More data on the way to learning CAS. This time I want to know how many different application versions are out there. Plus, what is the range of dates they are providing.
Remove old histograms.
cc @tomverran
> Get a count of App IDs and expiry dates

- build.sbt
- src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
- src/main/scala/com/gu/subscriptions/cas/config/Zuora.scala
I have bumped membership common so the refactoring is complete.
I also added a prodrun as well as devrun so we can test more easily.
@paulbrown1982 any comments please?
> bump to membership common without the old code

- src/main/scala/com/gu/subscriptions/cas/service/SubscriptionService.scala
Fixed bug where we did not handle errors thrown by calling the unsafe .plan lazy val on a subscription. Now rather than calling .plan we've assumed it's deprecated and instead use the new GetCurrentPlans helper object, simply echoing any error messages to the info log, and returning an empty list of current plans if so.
Did some opportunistic refactoring while the box was opened.
cc @jacobwinch @johnduffell @pvighi
> Fixed bug with authenticating cancelled plans

- src/main/scala/com/gu/subscriptions/cas/service/SubscriptionService.scala
> Should have been Future.successful

- build.sbt
- src/main/scala/com/gu/subscriptions/cas/bootstrap/CASService.scala
- src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/model/EmergencyTokens.scala
- src/main/scala/com/gu/subscriptions/cas/model/SubscriptionExpiration.scala
- src/main/scala/com/gu/subscriptions/cas/model/SubscriptionRequest.scala
- src/main/scala/com/gu/subscriptions/cas/model/TokenPayloadOps.scala
- src/main/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocol.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ZuoraDirectiveTest.scala
- src/test/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocolSpec.scala
If the subscription id starts with the emergency token prefix, then try to decode. If it cannot be decoded ( or it doesn't start with the prefix) get the sub info from Zuora
@paulbrown1982 @johnduffell @jacobwinch
> Emergency tokens

- build.sbt
- cloudformation/content-authorisation-proxy.cf.json
- src/main/resources/DEV.conf
- src/main/resources/PROD.conf
- src/main/resources/application.conf
- src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
- src/main/scala/com/gu/subscriptions/cas/bootstrap/CASService.scala
- src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ErrorRoute.scala
- src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
- src/main/scala/com/gu/subscriptions/cas/model/AuthorisationRequest.scala
- src/main/scala/com/gu/subscriptions/cas/model/SubscriptionExpiration.scala
- src/main/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocol.scala
- src/main/scala/com/gu/subscriptions/cas/service/DataStore.scala
- src/main/scala/com/gu/subscriptions/cas/service/api/DataStore.scala
- src/test/scala/com/amazonaws/regions/AwsFakes.scala
- src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
> Remove legacy cas

- cloudformation/content-authorisation-proxy.cf.json
I forgot to commit this from my last PR, the max and min instances where switched in the PROD config
> fix to cloud formation template

- src/main/scala/com/gu/subscriptions/cas/service/SubscriptionService.scala
Issue mentioned in code review: https://github.com/guardian/content-authorisation-proxy/pull/72/files/683ecda1dd70d7db029fe572f7ee7138792567f7#diff-4d24e9454ceb263904c5b092c89e0c41
cc @johnduffell @pvighi @jacobwinch
> Tweak to save another thread being spawned

- build.sbt
- cloudformation/content-authorisation-proxy.cf.json
- cloudformation/resources/conf/upstart.conf
- src/main/resources/DEV.public.conf
- src/main/resources/PROD.public.conf
- src/main/resources/application.conf
equivalent changes in membership-workflow :
- [original PR](https://github.com/guardian/membership-workflow/pull/71)
- [fix #1](https://github.com/guardian/membership-workflow/pull/72)
- [fix #2](https://github.com/guardian/membership-workflow/pull/73)
@paulbrown1982 @jacobwinch
> refactor configuration to work with systemd

- README.md
- build.sbt
- src/test/scala/com/gu/subscriptions/cas/model/ContactOpsSpec.scala
Update to a newer version of membership-common 0.394.
+ bonus README update
> Update to membership-common 0.394

- README.md
- cloudformation/content-authorisation-proxy.cf.yaml
> Use encrypted configuration file
