build.sbt
src/main/resources/DEV.conf
src/main/resources/PROD.conf
src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/monitoring/CloudWatch.scala
src/main/scala/com/gu/subscriptions/cas/monitoring/Metrics.scala

Adds custome metrics to push to CloudWatch. This will allow us to count number of requests to the CAS service (and later the Zuora service). 
cc/ @rtyley

Add custom metrics to CloudWatch and push request uri.

---

cloudformation/content-authorisation-proxy.cf.json

As part of https://github.com/guardian/content-authorisation-proxy/pull/7 I missed updating the cloudformation script. This has now been applied to the stack.

Add PushMetrics to the cfn policy

---

src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala

Also removed the redirect code as we believe expect CAS or Zuora endpoints will not be redirects.
PR might be easier to read with `?w=1`

Restrict proxy to subs and auth endpoints and POST method only

---

cloudformation/content-authorisation-proxy.cf.json

While SSL is on the ELB it wasn't part of the cloudformation template. I therefore changed all the settings back in this PR: https://github.com/guardian/content-authorisation-proxy/pull/9 :crying_cat_face: 
This PR makes sure SSL is part of the cloudformation template. I have applied this to PROD with @rtyley

Ensure SSL is part of the cloudformation

---

src/main/resources/application.conf

so that we can point conten-auth.guardian.co.uk to the proxy (and it doesn't call itself!).

Updating the proxy url to the legacy app 

---

src/main/resources/application.conf
src/main/resources/logback.xml
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala

The logs were going to std.out so I've switched this to go to a log file. 
I've removed the some headers from the response from the request as Spray seems to ignore them and override it with its own headers. This causes a lot of warnings in the logs which is just noise.

Logging changes

---

src/main/resources/application.conf
src/main/scala/com/gu/subscriptions/cas/bootstrap/CASService.scala
src/main/scala/com/gu/subscriptions/cas/bootstrap/SentryLogging.scala
src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
src/main/scala/com/gu/subscriptions/cas/directives/CheckSentryErrors.scala

- Include config file with Sentry credentials within the `application.conf` file.
- Also adds a temporary endpoint to test Sentry integration by triggering a divide by zero exception. We will remove it at the next deployment.
@rtyley @tudorraul

Include /etc/gu/cas-proxy.conf in application.conf

---

cloudformation/resources/conf/logger.conf

Because of a filename change cloud-watch has stopped collecting cas-proxy logs since June the 3th. This fixes the config and should allow Cloudwatch to resume collecting our logs.

Fix filename in cloudformation logger config

---

src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/monitoring/CloudWatch.scala
src/main/scala/com/gu/subscriptions/cas/monitoring/Metrics.scala

This allows us to factor out the 500 received from the legacy service from the ones CAS proxy returns.

Metrics for the CAS legacy service

---

src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

This is making the request proxying to CAS more modular, and adds some tests to the request and response transformations.

Test request and response transformation during proxying

---

src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/directives/ResponseCodeTransformer.scala
src/main/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocol.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
src/test/scala/com/gu/subscriptions/cas/directives/ResponseCodeTransformerSpec.scala
src/test/scala/com/gu/subscriptions/cas/model/json/CASErrorExpirationProtocolSpec.scala

This is another attempt at the PR https://github.com/guardian/content-authorisation-proxy/pull/22/files
which aimed at testing the request and response transformation while proxying.
Also adds the correct response codes after proxying to CAS, when possible. This is due to CAS sometimes sending 200 responses even in the presence of errors, relying on an error code mapping defined in https://github.com/guardian/content-authorisation/blob/master/content-authorisation/src/main/resources/conf/global.properties
This previously failed due to the casRoute function in ProxyDirective
`ctx => complete(...)`
instead of
`ctx => ctx.complete(...)`

Error handling

---

src/main/scala/com/gu/subscriptions/cas/model/SubscriptionExpiration.scala

https://trello.com/c/LKZZGejH/99-incorrect-sub-type-returned-from-cas-proxy-for-direct-debit-subscriptions
With this change, `expiryType` is now `sub`, as expected by Guardian IOS mobile apps.
```
$ curl -H "Content-Type:application/json; charset=UTF-8" -d "{ \"appId\" : \"touchpoint-membership\", \"deviceId\" : \"ROBERTO MADE THIS UP\", \"subscriberd\" : \"A-S00013340\", \"password\" : \"E8123\"}" http://localhost:9300/subs
{
"expiry": {
"expiryType": "sub",
"expiryDate": "2016-08-08"
}
}
```
cc @tudorraul @TesterSpike

Return 'sub' for the expiry type, just like legacy CAS

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/service/ZuoraSubscriptionService.scala

Zuora will create an expired record for the subscription every time there is a change to the subscription which will hold the old data.  We should filter these records out when determining the subscription date.
This change ensures we consider only the latest version of a subscription to infer it's cancellation date.

Fix incorrect cancellation date returned by CAS proxy

---

src/main/resources/touchpoint.PROD.conf

Following on from the conversation with @TesterSpike and Jason Burr - the CAS proxy is now pointing at PROD. The only testing we can now do end-to-end on subscribe.theguardian.com (from _sign-up_ to _redeeming on a real live mobile device_) is currently as PROD users.
The non-source controlled credentials in `/etc/gu/cas-proxy.conf` have already been updated to PROD values, but the source-controlled public url was pointing to the UAT environment.
It's better to put UAT credentials and values under a UAT config stanza, rather than put them under the PROD stanza and point them to UAT!
cc @ostapneko @vivekkr

Fix the PROD url for Zuora so that it is actually PROD

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/directives/ErrorRoute.scala
src/main/scala/com/gu/subscriptions/cas/directives/HealthCheckDirective.scala
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/service/zuora/ZuoraSubscriptionService.scala
src/test/scala/com/gu/subscriptions/cas/service/ZuoraSubscriptionServiceTest.scala

This is needed as part of the fix for https://trello.com/c/L4RKJH74/153-fix-the-cas-proxy
We think that it was due to the Zuora client not being fully initialised. This includes a Zuora service readiness check as part of the healthcheck.

Add Zuora readiness check as part of healthcheck

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/config/Zuora.scala
src/main/scala/com/gu/subscriptions/cas/service/zuora/ZuoraSubscriptionService.scala

CAS proxy is a spray app and there were some dependencies on a play akka context in membership common, therefore had to bump the version number to the latest common release and moved the zuora client out of configuration namespace.

Membership common depending on play Akka system

---

cloudformation/content-authorisation-proxy.cf.json

A new certificate has been issued for the cas proxy and cas legecy ELBs to use, the cert informaiton can be found https://trello.com/c/G5T24UEA/146-update-ssl-certificates-for-cas-legacy-proxy-servers this change is simply to update the cloud formation config to use the correct certificate.

Updated the cloud formation certificate name

---

build.sbt
src/main/resources/application.conf
src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/model/ResponseComparer.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

In the interim while we have a new and old version of CAS running then we need to ensure that the requests to both systems that don't have side effects (i.e. /subs requests) return the same responses. This change will temporarily send requests to both versions of CAS and compare the responses.

Switch cas proxy url

---

cloudformation/content-authorisation-proxy.cf.json
src/main/resources/application.conf

The new instance of CAS now has the correct ccas-legacy.subscriptions.guardianapis.com domain name and the *.subscriptions.guardianapis SSL certificate added to it. Therefore we can now point CAS proxy to this address using https
Updating AMI to fix critical security vulnerability: https://googleonlinesecurity.blogspot.co.uk/2016/02/cve-2015-7547-glibc-getaddrinfo-stack.html
/cc @tomverran

New CAS instance now has correct domain name an certificate + update AMI

---

README.md
build.sbt
src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
src/main/scala/com/gu/subscriptions/cas/config/Zuora.scala
src/main/scala/com/gu/subscriptions/cas/service/SubscriptionService.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

CAS proxy doesn't do much with Zuora but we should update it to use the same WSDL as everything else

Zuora wsdl 70

---

cloudformation/content-authorisation-proxy.cf.json

I've also created a RunScope test specifically for testing that the cert is valid:
https://www.runscope.com/radar/f862w29p8z5f/269ef569-b843-4d73-816b-1c2a519e4354/overview
See also:
https://trello.com/c/G5T24UEA/124-update-ssl-certificates-for-cas-legacy-proxy-servers
cc @chrisjowen @davidfurey

Update our Cloudformation to use the correct SSL certificate

---

src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

The Zuora versions of QSS subs for some reason no longer have leading zeros...

Drop leading zeros when querying subs in Zuora

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/monitoring/Histogram.scala

Adding a histogram cache of the requested set of subscription IDs which logs to CloudWatch every hour.
This is to see why a majority of traffic gets cascaded through to CAS when, given that we've migrated all digipack subs, I wouldn't expect to happen.
I suspect it might be requests for an empty Subscription ID.
https://trello.com/c/Tt0p2veS/571-spike-cas-legacy-not-seeing-drop-in-traffic-since-digipack-migration
cc @tomverran

Spike: why are a lot of requests getting cascaded?

---

build.sbt
src/main/resources/application.conf
src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
src/main/scala/com/gu/subscriptions/cas/directives/ErrorRoute.scala
src/main/scala/com/gu/subscriptions/cas/directives/HealthCheckDirective.scala
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/model/SubscriptionExpiration.scala
src/main/scala/com/gu/subscriptions/cas/model/SubscriptionRequest.scala
src/main/scala/com/gu/subscriptions/cas/service/SubscriptionService.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
src/test/scala/com/gu/subscriptions/cas/directives/ZuoraDirectiveTest.scala
src/test/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocolSpec.scala

- Added changes needed for paper plus-package subs to get digipacks
- Most of the changes are collateral from making password optional (ready for the below).
- Added TODO comments which describe the changes for how this app can start handling legacy CAS's auth calls.
- Backported the error codes from legacy CAS and put them in the error response.
cc @tomverran @nlindblad @mario-galic

Added changes needed for paper plus-package subs to get digipacks

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/directives/ZuoraDirective.scala
src/main/scala/com/gu/subscriptions/cas/model/SubscriptionRequest.scala
src/main/scala/com/gu/subscriptions/cas/model/json/ModelJsonProtocol.scala
src/main/scala/com/gu/subscriptions/cas/monitoring/Histogram.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
src/test/scala/com/gu/subscriptions/cas/directives/ZuoraDirectiveTest.scala

- Added more logging to see what authType is getting passed in to /auth or /subs - this will help determine whether they are coupled in any way (and need to share the same datastore post migration).
- Added logging to see if any subscriberIds are passed in to /auth - this will highlight any dodgy clients.
- Removed the old logging from /subs.
cc @tomverran

Histogram for auth

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
src/main/scala/com/gu/subscriptions/cas/config/Configuration.scala
src/main/scala/com/gu/subscriptions/cas/config/Zuora.scala
src/main/scala/com/gu/subscriptions/cas/directives/ProxyDirective.scala
src/main/scala/com/gu/subscriptions/cas/service/SubscriptionService.scala
src/main/scala/com/gu/subscriptions/cas/service/api/SubscriptionService.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

- Updated CAS Proxy to use new v2 Membership Common service classes, this makes it compatible once the old v1 classes get deleted.
- Added a weak test to the ProxyDirectiveSpec to also check that paper subs with a Digital Pack charge line also get approved if the 'password' is correct.
cc  @jacobwinch @johnduffell @pvighi @mario-galic

Update to latest membership common

---

build.sbt
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala
src/test/scala/com/gu/subscriptions/cas/model/ContactOpsSpec.scala

Im not very familiar with this project but it  loads the catalog on startup and logs an error if guardian weekly 1 year is defined. I'm not sure if that breaks anything.
I tested doing the same post the runscope test is doing but I'm not sure how much more testing we need for this since this update is bringing a few other changes  in addition to mine
@paulbrown1982

update membership common

---

cloudformation/content-authorisation-proxy.cf.json

The `sites.guardian.co.uk` Comodo cert was due to expire on 7th January 2017, so we needed to update the cert. Rather than renewing, we've CNAME'd `content-auth.guardian.co.uk` to Fastly - so Mobile Apps are now hitting https://content-auth.guardian.co.uk/sub on Fastly which has a valid SSL cert for that domain.
As for the ELB (which is [accessed as cas.subscriptions.guardianapis.com by Fastly](https://manage.fastly.com/configure/services/4k4rlHD5JDSJjvs4K1iQmW/diff/3,4)), this change updates it to use an [ACM cert for *.subscriptions.guardianapis.com](https://eu-west-1.console.aws.amazon.com/acm/home?region=eu-west-1#/?id=4055df40-9561-423c-962b-f78f3ce70434).
This cloud-formation has already been applied, and all [Runscope tests](https://www.runscope.com/radar/f862w29p8z5f) are green: …

Use an ACM cert, now we no longer need a .guardian.co.uk cert on the ELB

---

build.sbt
src/main/scala/com/gu/subscriptions/cas/bootstrap/Bootstrap.scala
src/main/scala/com/gu/subscriptions/cas/config/Zuora.scala
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

This PR pulls in the latest membership common version, which allows CAS to 'understand' Subs with a 'Semi_Annual' billing period.
It turns out that @pvighi already added the concept of a ZBillingPeriod (which includes 'Semi_Annual') to SubJsonReads (in https://github.com/guardian/membership-common/pull/367). 
I've tested that CAS still responds correctly to a standard Digipack sub, and am also able to successfully lookup a migrated Voucher+ sub with a Semi_Annual billing period, so bumping the membership-common version seems to be sufficient for a short-term fix.
@paulbrown1982

Update membership common version

---

build.sbt
src/test/scala/com/gu/subscriptions/cas/directives/ProxyDirectiveSpec.scala

https://github.com/guardian/membership-common/pull/419 understand free id
edit:
guardian/membership-common#424 don't read the untagged rateplans
guardian/membership-common#425 use billing period as an object not a case class

use membership common that understands frontend ids

---

src/main/scala/com/gu/subscriptions/cas/service/DataStore.scala

the dynamo table that holds auth data is configured to clean up entries automatically according to the ttlTimestamp attribute [dynamo TTL feature doc](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/howitworks-ttl.html).
The value was set in milliseconds since the unix epoch but amazon expects it to be in seconds since the epoch, which makes the first item to be cleaned from the table around the year 50210.
This fixes it so that we set the ttl in the correct format. A script will be run to fix the existing data in the table.
@johnduffell @AWare @jacobwinch @paulbrown1982 @lmath

set ttl timestamp in seconds since epoch instead of mills

---

cloudformation/content-authorisation-proxy.cf.yaml
src/main/resources/DEV.public.conf
src/main/resources/PROD.public.conf

the encrypted dynamo table daily-edition-trial-periods-PROD is already created and populated with all the data that was in CAS-auth-PROD as of this morning around 10:46.
The people we miss in the switch from one table to the other would just get a new trial period so worst case scenario they get one extra day in their trial period.
We will remove the unencrypted dynamodb table when we are confident that we will not need to back to it

Use Encrypted dynamo table

---

cloudformation/content-authorisation-proxy.cf.yaml

Remove the cas-auth-PROD table that is not being used anymore since we merged https://github.com/guardian/content-authorisation-proxy/pull/84

remove old unencrypted dynamo table
